language: cpp
dist: bionic
os: linux

compiler:
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
  jobs:
    - YARP_CHECKOUT=yarp-3.3
    - YARP_CHECKOUT=yarp-3.2

jobs:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=master
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=master

cache:
  directories: $CACHE_DIR

addons:
  apt:
    packages:
    - libopencv-dev
    - libpcl-dev
    - libproj-dev # needed by libpcl-dev on Xenial (known bug)

    # ECF
    - libboost-dev
    - libtool
    - dh-autoreconf

    # YARP and KDL
    - libeigen3-dev

    # OpenRAVE
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-python-dev
    - libboost-thread-dev
    - libboost-iostreams-dev
    - libqt4-dev
    - qt4-dev-tools
    - libxml2-dev
    - libode-dev
    - libsoqt4-dev
    - libcoin80-dev

    # Aquila
    - libsfml-dev

    # unit testing
    - libgtest-dev

    # code coverage
    - lcov

before_install:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

install:
  #-- Install ECF
  - source "$TRAVIS_BUILD_DIR/scripts/travis/cache-ecf.sh"

  #-- Install YARP
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

  #-- Install OpenRAVE
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name OpenRAVE
    --repo-url https://github.com/rdiankov/openrave
    --repo-checkout master
    --additional-cmake-options "-DOPT_VIDEORECORDING:BOOL=OFF -DOPT_IKFAST_FLOAT32:BOOL=OFF"
    --prepend-to-linker-path lib
    --cmake-env 'CFLAGS="-w" CXXFLAGS="-w"'

  #-- Install KDL
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name KDL
    --repo-url https://github.com/orocos/orocos_kinematics_dynamics
    --repo-checkout master
    --cmake-home-dir orocos_kdl
    --prepend-to-linker-path lib

  #-- Install Aquila
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name Aquila
    --repo-url https://github.com/zsiciarz/aquila
    --repo-checkout master
    --prepend-to-linker-path lib
    --additional-export-paths AQUILA_DIR

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install" -DENABLE_coverage:BOOL=ON
  - make install
  - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH

script:
  - echo "No unit tests available"

after_success:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then source "$TRAVIS_BUILD_DIR/scripts/travis/coverage.sh"; fi

  - make uninstall
