language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
  matrix:
    - YARP_CHECKOUT=master
    - YARP_CHECKOUT=30dce54 # hotfix for v3.0.1
    - YARP_CHECKOUT=v2.3.72.1
    - YARP_CHECKOUT=v2.3.70.2

matrix:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=devel
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=devel

cache:
  directories: $CACHE_DIR

addons:
  apt:
    packages:
    - libopencv-dev

    # ECF
    - libboost-dev
    - libtool
    - dh-autoreconf

    # YARP and KDL
    - libeigen3-dev

    # OpenRAVE
    - libboost-all-dev
    - libqt4-dev
    - qt4-dev-tools
    - libxml2-dev
    - libode-dev
    - libsoqt4-dev
    - libcoin80-dev

    # Aquila
    - libsfml-dev

    # unit testing
    - libgtest-dev

    # code coverage
    - lcov

before_install:
  #-- Configure Git (needed by YCM)
  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

  #-- Add source repository for PCL-related packages
  - sudo add-apt-repository --yes ppa:v-launchpad-jochen-sprickerhof-de/pcl
  - sudo apt-get -qq update

  #-- Install PCL
  - sudo apt-get install libpcl-all-dev

  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

install:
  #-- Install ECF
  - source "$TRAVIS_BUILD_DIR/scripts/travis/cache-ecf.sh"

  #-- Install YARP
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

  #-- Install OpenRAVE
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name OpenRAVE
    --repo-url https://github.com/rdiankov/openrave
    --repo-checkout master
    --prepend-to-linker-path lib

  #-- Install KDL
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name KDL
    --repo-url https://github.com/orocos/orocos_kinematics_dynamics
    --repo-checkout master
    --cmake-home-dir orocos_kdl
    --prepend-to-linker-path lib

  #-- Install Aquila
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name Aquila
    --repo-url https://github.com/zsiciarz/aquila
    --repo-checkout master
    --prepend-to-linker-path lib
    --additional-export-paths AQUILA_DIR

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install" -DENABLE_coverage:BOOL=ON
  - make install
  - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH

script:
  - echo "No unit tests available"

after_success:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then source "$TRAVIS_BUILD_DIR/scripts/travis/coverage.sh"; fi

  - make uninstall
